Medication.create(name: "Sample", dosage: "50mg", url: 'http://health.nih.gov/')
user = User.create(username: "Grant", password: "123")
m1 = Medication.create(name: "Hydrocodone", dosage: "5mg", url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a601006.html')
m2 = Medication.create(name: "Lisinopril", dosage: '20mg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a692051.html')
m3 = Medication.create(name: "Synthroid", dosage: '50mcg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a682461.html')
m4 = Medication.create(name: "Norvasc", dosage: '5mg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a692044.html')
m5 = Medication.create(name: "Prilosec", dosage: '20mg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a693050.html')
m6 = Medication.create(name: "Azithromycin", dosage: '500mg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a697037.html')
m7 = Medication.create(name: "Amoxicillin", dosage: '500 mg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a685001.html')
m8 = Medication.create(name: "Glucophage", dosage: '2000mg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a696005.html')
m9 = Medication.create(name: "Hydrochlorothiazide", dosage: '50mg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a682571.html')
m10 = Medication.create(name: "Selegiline", dosage: "5mg", url: "http://www.nlm.nih.gov/medlineplus/druginfo/meds/a697046.html")

UserMedication.create(user: user, medication: m1, day: "Sunday")
UserMedication.create(user: user, medication: m2, day: "Monday", times_per_day: 2)
UserMedication.create(user: user, medication: m3, alias: 'Levothyroxine')
UserMedication.create(user: user, medication: m4, alias: 'Amlodipine')
UserMedication.create(user: user, medication: m5, alias: 'Omeprazole')
UserMedication.create(user: user, medication: m6)
UserMedication.create(user: user, medication: m7)
UserMedication.create(user: user, medication: m8, alias: 'Metformin')
UserMedication.create(user: user, medication: m9)
UserMedication.create(user: user, medication: m10)

