Medication.create(name: "Sample", dosage: "50mg", url: 'http://health.nih.gov/')
user = User.create(username: "Grant", password: "123")
m1 = Medication.create(name: "Hydrocodone", dosage: "5mg", url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a601006.html')
m2 = Medication.create(name: "Lisinopril", dosage: '20mg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a692051.html')
m3 = Medication.create(name: "Synthroid", dosage: '50mcg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a682461.html')
m4 = Medication.create(name: "Norvasc", dosage: '5mg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a692044.html')
m5 = Medication.create(name: "Prilosec", dosage: '20mg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a693050.html')
# m6 = Medication.create(name: "Azithromycin", dosage: '500mg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a697037.html')
# m7 = Medication.create(name: "Amoxicillin", dosage: '500 mg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a685001.html')
m8 = Medication.create(name: "Glucophage", dosage: '2000mg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a696005.html')
m9 = Medication.create(name: "Hydrochlorothiazide", dosage: '50mg', url: 'http://www.nlm.nih.gov/medlineplus/druginfo/meds/a682571.html')
m10 = Medication.create(name: "Selegiline", dosage: "5mg", url: "http://www.nlm.nih.gov/medlineplus/druginfo/meds/a697046.html")

UserMedication.create(user: user, medication: m1, day: "Sunday")
UserMedication.create(user: user, medication: m1, day: "Thursday")
UserMedication.create(user: user, medication: m2, day: "Monday", times_per_day: 2, color: "#333333")
UserMedication.create(user: user, medication: m3, alias: 'Levothyroxine')
UserMedication.create(user: user, medication: m4, alias: 'Amlodipine', color: "#00E5EE")
UserMedication.create(user: user, medication: m5, alias: 'Omeprazole', color: "#333333")
# UserMedication.create(user: user, medication: m6)
# UserMedication.create(user: user, medication: m7)
UserMedication.create(user: user, medication: m8, alias: 'Metformin')
UserMedication.create(user: user, medication: m9, color: "#f4f3f2")
UserMedication.create(user: user, medication: m10, color: "#333333")

p1 = Post.create(author: user, title: "Don't use Metformin", content: "I had a very strong reaction to Metformin. Muscle pain or weakness; numb or cold feeling in your arms and legs; trouble breathing; feeling dizzy, light-headed, tired, or very weak; stomach pain, nausea with vomiting; or slow or uneven heart rate.")
PostMedication.create(post: p1, medication: m8)
p2 = Post.create(author: user, title: "Highly recommend Lisinopril", content:  "This drug helped me treat hypertension, congestive heart failure and to improve survival after a heart attack.")
PostMedication.create(post: p2, medication: m2)

